name: Build

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/5 15,16,17,18,19,20,21,22,23 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Do everything
      run: |
        pip3 install requests
        python3 scan.py
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
